# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(812, 623)
        MainWindow.setStyleSheet("QGraphicsView#background {\n"
"    background-color: rgb(40, 32, 32);\n"
"    border: rgb(40, 32, 32);\n"
"}\n"
"\n"
"QGraphicsView#topbar {\n"
"    background-color: rgb(30, 22, 22);\n"
"    border: rgb(30, 22, 22);\n"
"}\n"
"\n"
"QGraphicsView#window {\n"
"    background-color: rgb(30, 22, 22);\n"
"    border: rgb(30, 22, 22);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: rgb(30, 22, 22);\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 18px;\n"
"    padding: 5px;\n"
"    border-radius: 10px;\n"
"    border: 2px solid white;\n"
"}\n"
"QLineEdit:focus {\n"
"    background-color: rgb(181, 181, 181);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    background-color: rgb(60, 52, 52);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QLabel {\n"
"    color: rgb(255, 255, 255);\n"
"    font: 9pt \"Arial\";\n"
"}\n"
"\n"
"QLabel#status_label {\n"
"    color: rgb(254, 0, 0);\n"
"    font: 9pt \"Arial\";\n"
"}\n"
"\n"
"QCheckBox {\n"
"    color: rgb(255, 255, 255);\n"
"    font: 9pt \"Arial\";\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: rgb(40, 32, 32);\n"
"    color: white;               /* Texte blanc */\n"
"    border-radius: 10px;\n"
"    border: 2px solid red;\n"
"    padding: 10px 20px;         /* Ajoute de l\'espace autour du texte */\n"
"    font-size: 16px;            /* Taille du texte */\n"
"    font: 9pt \"Arial\";\n"
"}\n"
"\n"
"QPushButton#sign_in_button {\n"
"    background-color: none;\n"
"    border: none;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(60, 52, 52);\n"
"}\n"
"\n"
"QPushButton:hover#sign_in_button {\n"
"    color: red;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(234, 60, 60);\n"
"}\n"
"\n"
"QPushButton:pressed#sign_in_button {\n"
"    color: rgb(255, 148, 148);\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #C0C0C0;  /* Couleur grisée lorsque désactivé */\n"
"    color: #F0F0F0;             /* Texte un peu plus clair quand désactivé */\n"
"}\n"
"\n"
"QOpenGLWidget {\n"
"    background-color: rgb(40, 32, 32);\n"
"    border-radius: 10px;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.background = QtWidgets.QGraphicsView(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(0, -30, 811, 621))
        self.background.setStyleSheet("background {\n"
"rgb(40, 32, 32)\n"
"}")
        self.background.setObjectName("background")
        self.titre = QtWidgets.QLabel(self.centralwidget)
        self.titre.setGeometry(QtCore.QRect(0, 120, 811, 31))
        self.titre.setObjectName("titre")
        self.username = QtWidgets.QLabel(self.centralwidget)
        self.username.setGeometry(QtCore.QRect(270, 190, 91, 31))
        self.username.setObjectName("username")
        self.usernameEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.usernameEdit.setGeometry(QtCore.QRect(280, 220, 261, 41))
        self.usernameEdit.setText("")
        self.usernameEdit.setObjectName("usernameEdit")
        self.topbar = QtWidgets.QGraphicsView(self.centralwidget)
        self.topbar.setGeometry(QtCore.QRect(0, 0, 811, 71))
        self.topbar.setStyleSheet("QGraphicsView {\n"
"    color: rgb(30, 22, 22);\n"
"}")
        self.topbar.setObjectName("topbar")
        self.submitButton = QtWidgets.QPushButton(self.centralwidget)
        self.submitButton.setGeometry(QtCore.QRect(300, 460, 221, 51))
        self.submitButton.setObjectName("submitButton")
        self.sign_in_button = QtWidgets.QPushButton(self.centralwidget)
        self.sign_in_button.setGeometry(QtCore.QRect(300, 510, 221, 41))
        self.sign_in_button.setObjectName("sign_in_button")
        self.window = QtWidgets.QGraphicsView(self.centralwidget)
        self.window.setGeometry(QtCore.QRect(210, 100, 401, 451))
        self.window.setStyleSheet("")
        self.window.setObjectName("window")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(220, 150, 381, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.password = QtWidgets.QLabel(self.centralwidget)
        self.password.setGeometry(QtCore.QRect(270, 280, 91, 31))
        self.password.setObjectName("password")
        self.passwordEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.passwordEdit.setGeometry(QtCore.QRect(280, 310, 261, 41))
        self.passwordEdit.setText("")
        self.passwordEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordEdit.setObjectName("passwordEdit")
        self.status_label = QtWidgets.QLabel(self.centralwidget)
        self.status_label.setGeometry(QtCore.QRect(270, 160, 281, 31))
        self.status_label.setObjectName("status_label")
        self.background.raise_()
        self.window.raise_()
        self.titre.raise_()
        self.username.raise_()
        self.usernameEdit.raise_()
        self.topbar.raise_()
        self.submitButton.raise_()
        self.sign_in_button.raise_()
        self.line.raise_()
        self.password.raise_()
        self.passwordEdit.raise_()
        self.status_label.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 812, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.titre.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">Connect</span></p></body></html>"))
        self.username.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Username</p></body></html>"))
        self.submitButton.setText(_translate("MainWindow", "Submit"))
        self.sign_in_button.setText(_translate("MainWindow", "Not registered yet ? Sign in"))
        self.password.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Password</p></body></html>"))
        self.status_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
