# Form implementation generated from reading ui file 'c:\Users\louen\Documents\BUT2\SAE_S3\TrackMyPrompt\TrackMyPrompt\ui\history.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(812, 623)
        MainWindow.setStyleSheet("QGraphicsView#background {\n"
"    background-color: rgb(30, 22, 22);\n"
"    border: rgb(30, 22, 22);\n"
"}\n"
"\n"
"QGraphicsView#topbar {\n"
"    background-color: rgb(30, 22, 22);\n"
"    border: rgb(30, 22, 22);\n"
"}\n"
"\n"
"QGraphicsView#window {\n"
"    background-color: rgb(30, 22, 22);\n"
"    border: rgb(30, 22, 22);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QTableView {\n"
"    background-color: rgb(40, 32, 32);\n"
"    border: rgb(40, 32, 32);\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 18px;\n"
"    \n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: rgb(30, 22, 22);\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 18px;\n"
"    padding: 5px;\n"
"    border:None;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    background-color: rgb(60, 52, 52);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    background-color: rgb(60, 52, 52);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QLabel {\n"
"    color: rgb(255, 255, 255);\n"
"    font: 9pt \"Arial\";\n"
"}\n"
"\n"
"QLabel#status_label {\n"
"    color: rgb(254, 0, 0);\n"
"    font: 9pt \"Arial\";\n"
"}\n"
"\n"
"QCheckBox {\n"
"    color: rgb(255, 255, 255);\n"
"    font: 9pt \"Arial\";\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: rgb(40, 32, 32);\n"
"    color: white;               /* Texte blanc */\n"
"    border-radius: 10px;\n"
"    border: 2px solid red;\n"
"    padding: 10px 20px;         /* Ajoute de l\'espace autour du texte */\n"
"    font-size: 16px;            /* Taille du texte */\n"
"    font: 9pt \"Arial\";\n"
"}\n"
"\n"
"QPushButton#sign_in_button {\n"
"    background-color: none;\n"
"    border: none;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(60, 52, 52);\n"
"}\n"
"\n"
"QPushButton:hover#sign_in_button {\n"
"    color: red;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(234, 60, 60);\n"
"}\n"
"\n"
"QPushButton:pressed#sign_in_button {\n"
"    color: rgb(255, 148, 148);\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #C0C0C0;  /* Couleur grisée lorsque désactivé */\n"
"    color: #F0F0F0;             /* Texte un peu plus clair quand désactivé */\n"
"}\n"
"\n"
"QOpenGLWidget {\n"
"    background-color: rgb(40, 32, 32);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QToolButton {\n"
"    background-color: rgb(30, 22, 22);\n"
"}\n"
"\n"
"QToolButton:hover {\n"
"    background-color: rgb(60, 52, 52);\n"
"}\n"
"\n"
"QToolButton:pressed {\n"
"    background-color: rgb(90, 82, 82);\n"
"}\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.background = QtWidgets.QGraphicsView(parent=self.centralwidget)
        self.background.setGeometry(QtCore.QRect(0, -30, 811, 621))
        self.background.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.CustomContextMenu)
        self.background.setAutoFillBackground(False)
        self.background.setStyleSheet("background {\n"
"rgb(40, 32, 32)\n"
"}")
        self.background.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.background.setObjectName("background")
        self.usernameEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.usernameEdit.setGeometry(QtCore.QRect(0, 0, 721, 71))
        self.usernameEdit.setText("")
        self.usernameEdit.setObjectName("usernameEdit")
        self.topbar = QtWidgets.QGraphicsView(parent=self.centralwidget)
        self.topbar.setGeometry(QtCore.QRect(0, 0, 811, 71))
        self.topbar.setStyleSheet("QGraphicsView {\n"
"    color: rgb(30, 22, 22);\n"
"}")
        self.topbar.setObjectName("topbar")
        self.status_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.status_label.setGeometry(QtCore.QRect(270, 160, 281, 31))
        self.status_label.setObjectName("status_label")
        self.toolButton = QtWidgets.QToolButton(parent=self.centralwidget)
        self.toolButton.setGeometry(QtCore.QRect(720, 0, 91, 71))
        self.toolButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.toolButton.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.ActionsContextMenu)
        self.toolButton.setAcceptDrops(False)
        self.toolButton.setStatusTip("")
        self.toolButton.setLocale(QtCore.QLocale(QtCore.QLocale.Language.French, QtCore.QLocale.Country.France))
        self.toolButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Burger.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.toolButton.setIcon(icon)
        self.toolButton.setIconSize(QtCore.QSize(70, 70))
        self.toolButton.setPopupMode(QtWidgets.QToolButton.ToolButtonPopupMode.InstantPopup)
        self.toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonIconOnly)
        self.toolButton.setAutoRaise(False)
        self.toolButton.setObjectName("toolButton")
        self.tableView = QtWidgets.QTableView(parent=self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(80, 120, 651, 421))
        self.tableView.setObjectName("tableView")
        self.background.raise_()
        self.topbar.raise_()
        self.usernameEdit.raise_()
        self.status_label.raise_()
        self.toolButton.raise_()
        self.tableView.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.usernameEdit.setPlaceholderText(_translate("MainWindow", "Rechercher un historique..."))
        self.status_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
